import { Meal } from "@/types";

export const meals: Meal[] = [
  // ─── DINNERS ────────────────────────────────────────────────────────────────
  {
    id: "herb-roasted-chicken",
    name: "Herb Roasted Chicken",
    description:
      "Free-range chicken roasted with fresh rosemary, thyme, and garlic over seasonal root vegetables.",
    longDescription:
      "Our free-range chicken is dry-brined overnight then slow-roasted to golden perfection with a fragrant blend of fresh rosemary, thyme, and whole garlic cloves. Served alongside caramelized root vegetables — parsnips, carrots, and sweet potato — finished with a rich pan-dripping jus. Everything you need arrives pre-prepped and ready to roast.",
    category: "dinner",
    dayOfWeek: "Monday",
    images: [
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c1?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559847844-5315695dadae?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 520,
      protein: 48,
      carbs: 22,
      fat: 26,
      fiber: 4,
      sodium: 680,
    },
    pricing: { serves1: 16.99, serves2: 29.99, family: 54.99 },
    prepTime: "15 min",
    cookTime: "45 min",
    tags: ["Gluten-Free", "High Protein"],
    allergens: ["None"],
    ingredients: [
      "Free-range chicken",
      "Fresh rosemary",
      "Fresh thyme",
      "Garlic",
      "Parsnips",
      "Carrots",
      "Sweet potato",
      "Olive oil",
      "Sea salt",
      "Black pepper",
    ],
    isPopular: true,
  },
  {
    id: "seared-salmon",
    name: "Seared Salmon with Lemon Butter Sauce",
    description:
      "Atlantic salmon fillets seared to crispy perfection with a bright lemon butter sauce and broccolini.",
    longDescription:
      "Wild-caught Atlantic salmon fillets arrive skin-on and ready to sear. The bright lemon butter sauce — made with capers, fresh dill, and a splash of white wine — comes together in minutes in the same pan. Served with tender broccolini and herbed quinoa. A restaurant-quality weeknight dinner in under 30 minutes.",
    category: "dinner",
    dayOfWeek: "Tuesday",
    images: [
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1485704686097-ed47f7263ca4?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 480,
      protein: 42,
      carbs: 18,
      fat: 28,
      fiber: 3,
      sodium: 590,
    },
    pricing: { serves1: 19.99, serves2: 35.99, family: 64.99 },
    prepTime: "10 min",
    cookTime: "20 min",
    tags: ["Gluten-Free", "High Protein", "Omega-3"],
    allergens: ["Fish", "Dairy", "Sulfites"],
    ingredients: [
      "Wild-caught Atlantic salmon",
      "Lemon",
      "Unsalted butter",
      "Capers",
      "Fresh dill",
      "Dry white wine",
      "Broccolini",
      "Quinoa",
      "Olive oil",
      "Garlic",
    ],
    isNew: true,
  },
  {
    id: "beef-bolognese",
    name: "Classic Beef Bolognese",
    description:
      "Slow-simmered beef and pork ragù with hand-rolled pappardelle pasta and aged Parmigiano-Reggiano.",
    longDescription:
      "Our bolognese is made the traditional way — a blend of grass-fed beef and heritage pork, slow-braised in San Marzano tomatoes, dry red wine, and soffritto for deep, complex flavor. Paired with fresh hand-rolled pappardelle pasta and generously finished with aged Parmigiano-Reggiano. The sauce comes fully cooked; you just boil the pasta and assemble.",
    category: "dinner",
    dayOfWeek: "Wednesday",
    images: [
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 620,
      protein: 36,
      carbs: 68,
      fat: 22,
      fiber: 5,
      sodium: 780,
    },
    pricing: { serves1: 14.99, serves2: 26.99, family: 49.99 },
    prepTime: "10 min",
    cookTime: "20 min",
    tags: ["High Protein", "Classic"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    ingredients: [
      "Grass-fed ground beef",
      "Heritage ground pork",
      "San Marzano tomatoes",
      "Fresh pappardelle pasta",
      "Parmigiano-Reggiano",
      "Dry red wine",
      "Yellow onion",
      "Carrot",
      "Celery",
      "Fresh basil",
    ],
    isPopular: true,
  },
  {
    id: "mushroom-risotto",
    name: "Wild Mushroom Risotto",
    description:
      "Creamy Arborio risotto with a blend of wild mushrooms, truffle oil, and fresh Parmesan.",
    longDescription:
      "A vegetarian showstopper. We source a blend of seasonal wild mushrooms — porcini, chanterelle, and cremini — that are sautéed in butter and shallots before being folded into slowly ladled risotto. The dish is finished with a drizzle of white truffle oil and a generous handful of freshly grated Parmesan. All mise en place is done; just stir and serve.",
    category: "dinner",
    dayOfWeek: "Thursday",
    images: [
      "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1633352615955-9b407b072bc2?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 540,
      protein: 14,
      carbs: 72,
      fat: 22,
      fiber: 4,
      sodium: 640,
    },
    pricing: { serves1: 15.99, serves2: 28.99, family: 52.99 },
    prepTime: "10 min",
    cookTime: "30 min",
    tags: ["Vegetarian", "Gluten-Free"],
    allergens: ["Dairy"],
    ingredients: [
      "Arborio rice",
      "Porcini mushrooms",
      "Chanterelle mushrooms",
      "Cremini mushrooms",
      "Dry white wine",
      "Parmigiano-Reggiano",
      "Shallots",
      "Unsalted butter",
      "White truffle oil",
      "Fresh thyme",
    ],
  },
  {
    id: "pan-seared-steak",
    name: "Pan-Seared Ribeye with Truffle Frites",
    description:
      "12oz prime ribeye, dry-aged 28 days, with crispy truffle parmesan frites and herb compound butter.",
    longDescription:
      "A true date-night special. Our dry-aged prime ribeye arrives seasoned and ready to sear in minutes. The recipe walks you through achieving a perfect crust and desired internal temperature. Served with hand-cut truffle parmesan frites and a generous pat of roasted garlic herb compound butter that melts beautifully over the steak as it rests.",
    category: "dinner",
    dayOfWeek: "Friday",
    images: [
      "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1558030006-450675393462?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 680,
      protein: 52,
      carbs: 38,
      fat: 36,
      fiber: 4,
      sodium: 820,
    },
    pricing: { serves1: 24.99, serves2: 44.99, family: 79.99 },
    prepTime: "15 min",
    cookTime: "25 min",
    tags: ["High Protein", "Premium", "Date Night"],
    allergens: ["Dairy"],
    ingredients: [
      "28-day dry-aged prime ribeye",
      "Yukon gold potatoes",
      "White truffle oil",
      "Parmigiano-Reggiano",
      "Roasted garlic",
      "Fresh herbs (thyme, rosemary, parsley)",
      "Unsalted butter",
      "Fleur de sel",
      "Cracked black pepper",
    ],
    isPopular: true,
  },
  {
    id: "shrimp-tacos",
    name: "Chipotle Shrimp Tacos",
    description:
      "Smoky chipotle-marinated Gulf shrimp with mango-avocado salsa, slaw, and warm corn tortillas.",
    longDescription:
      "Gulf Coast shrimp marinated in a smoky chipotle-lime sauce arrive ready to sear in 5 minutes. Topped with a vibrant fresh mango and avocado salsa, house-made cilantro-lime slaw, and a drizzle of crema on warm stone-ground corn tortillas. Bright, fresh, and full of flavor — perfect for a casual Friday night.",
    category: "dinner",
    dayOfWeek: "Saturday",
    images: [
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512838243191-e81168acc5fe?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 490,
      protein: 34,
      carbs: 48,
      fat: 18,
      fiber: 6,
      sodium: 720,
    },
    pricing: { serves1: 16.99, serves2: 29.99, family: 54.99 },
    prepTime: "15 min",
    cookTime: "10 min",
    tags: ["Gluten-Free", "Dairy-Free"],
    allergens: ["Shellfish"],
    ingredients: [
      "Gulf shrimp",
      "Chipotle peppers in adobo",
      "Fresh mango",
      "Avocado",
      "Red cabbage",
      "Lime",
      "Fresh cilantro",
      "Stone-ground corn tortillas",
      "Mexican crema",
      "Red onion",
    ],
  },
  {
    id: "braised-short-ribs",
    name: "Red Wine Braised Short Ribs",
    description:
      "Slow-braised bone-in short ribs in a rich red wine reduction with creamy Yukon gold mash.",
    longDescription:
      "Our Sunday showstopper. Bone-in beef short ribs are braised low-and-slow in a deep red wine and beef stock reduction with aromatics until fork-tender and falling off the bone. The braise sauce is reduced to a glossy, intensely flavored glaze. Served over silky Yukon gold mashed potatoes with crispy fried shallots and fresh gremolata.",
    category: "dinner",
    dayOfWeek: "Sunday",
    images: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 720,
      protein: 54,
      carbs: 28,
      fat: 42,
      fiber: 3,
      sodium: 860,
    },
    pricing: { serves1: 22.99, serves2: 40.99, family: 74.99 },
    prepTime: "20 min",
    cookTime: "180 min",
    tags: ["High Protein", "Comfort Food", "Premium"],
    allergens: ["Dairy", "Sulfites"],
    ingredients: [
      "Bone-in beef short ribs",
      "Dry red wine",
      "Beef stock",
      "Yukon gold potatoes",
      "Unsalted butter",
      "Heavy cream",
      "Shallots",
      "Fresh thyme",
      "Rosemary",
      "Lemon zest",
    ],
    isPopular: true,
  },

  // ─── BREAKFAST ──────────────────────────────────────────────────────────────
  {
    id: "overnight-oats",
    name: "Overnight Oats with Berry Compote",
    description:
      "Creamy oats soaked overnight in oat milk with chia seeds, topped with warm berry compote and honey granola.",
    longDescription:
      "Steel-cut oats soaked overnight in house-made oat milk with chia seeds and a touch of vanilla. In the morning, top with our warm mixed berry compote — made from locally sourced strawberries, blueberries, and blackberries — and a sprinkle of honey-toasted granola for crunch. A nourishing, no-cook breakfast that's ready when you are.",
    category: "breakfast",
    images: [
      "https://images.unsplash.com/photo-1517673400267-0ac5ee01d40b?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 380,
      protein: 16,
      carbs: 58,
      fat: 10,
      fiber: 8,
      sodium: 180,
    },
    pricing: { serves1: 7.99, serves2: 13.99, family: 24.99 },
    prepTime: "10 min",
    cookTime: "0 min (overnight soak)",
    tags: ["Vegetarian", "High Fiber", "Make Ahead"],
    allergens: ["Gluten", "Tree Nuts"],
    ingredients: [
      "Steel-cut oats",
      "Oat milk",
      "Chia seeds",
      "Vanilla extract",
      "Strawberries",
      "Blueberries",
      "Blackberries",
      "Honey",
      "Granola",
      "Maple syrup",
    ],
    isNew: true,
  },
  {
    id: "avocado-toast",
    name: "Smashed Avocado Toast & Poached Eggs",
    description:
      "Sourdough toast with smashed avocado, poached eggs, everything bagel seasoning, and microgreens.",
    longDescription:
      "Thick-cut local sourdough is toasted then layered with generously smashed Hass avocado seasoned with lemon, flaky salt, and red pepper flakes. Topped with two perfectly poached eggs, everything bagel seasoning, radish, and a tangle of fresh microgreens. Step-by-step poached egg instructions included — easier than you think.",
    category: "breakfast",
    images: [
      "https://images.unsplash.com/photo-1541519227354-08fa5d50c820?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 420,
      protein: 18,
      carbs: 42,
      fat: 22,
      fiber: 9,
      sodium: 480,
    },
    pricing: { serves1: 9.99, serves2: 17.99, family: 31.99 },
    prepTime: "10 min",
    cookTime: "10 min",
    tags: ["Vegetarian", "High Fiber"],
    allergens: ["Gluten", "Eggs"],
    ingredients: [
      "Local sourdough bread",
      "Hass avocados",
      "Free-range eggs",
      "Lemon",
      "Everything bagel seasoning",
      "Red pepper flakes",
      "Radish",
      "Microgreens",
      "Olive oil",
      "Flaky sea salt",
    ],
    isPopular: true,
  },

  // ─── LUNCH / SNACKS ─────────────────────────────────────────────────────────
  {
    id: "greek-salad-chicken",
    name: "Greek Salad with Grilled Chicken",
    description:
      "Romaine and cucumber salad with grilled lemon herb chicken, Kalamata olives, and house tzatziki.",
    longDescription:
      "Crisp romaine and English cucumber tossed with cherry tomatoes, Kalamata olives, pepperoncini, and creamy feta. Topped with grilled lemon-herb marinated chicken breast and a generous dollop of house-made tzatziki. The chicken arrives pre-marinated; just grill and slice. A light but satisfying lunch that's ready in 15 minutes.",
    category: "lunch-snack",
    images: [
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1547496502-affa22d38842?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 420,
      protein: 32,
      carbs: 18,
      fat: 24,
      fiber: 5,
      sodium: 680,
    },
    pricing: { serves1: 10.99, serves2: 19.99, family: 35.99 },
    prepTime: "15 min",
    cookTime: "12 min",
    tags: ["Gluten-Free", "High Protein"],
    allergens: ["Dairy"],
    ingredients: [
      "Romaine lettuce",
      "Grilled chicken breast",
      "English cucumber",
      "Cherry tomatoes",
      "Kalamata olives",
      "Feta cheese",
      "Pepperoncini",
      "Greek yogurt",
      "Fresh dill",
      "Lemon",
    ],
  },
  {
    id: "trail-mix",
    name: "Artisan Trail Mix & Seasonal Fruit",
    description:
      "House-blend trail mix with activated nuts, dried fruit, dark chocolate, and seasonal cut fruit.",
    longDescription:
      "Our house trail mix features activated almonds, cashews, and walnuts with coconut flakes, tart dried cranberries, golden raisins, and 72% dark chocolate chunks. Paired with a generous portion of seasonally sourced fresh cut fruit — typically a mix of melon, berries, and citrus. Perfect for a mid-morning snack or school lunchbox.",
    category: "lunch-snack",
    images: [
      "https://images.unsplash.com/photo-1571748982800-fa51082c2224?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1564951434112-64d74cc2a2d7?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 340,
      protein: 10,
      carbs: 28,
      fat: 22,
      fiber: 4,
      sodium: 120,
    },
    pricing: { serves1: 5.99, serves2: 9.99, family: 17.99 },
    prepTime: "0 min",
    cookTime: "0 min",
    tags: ["Vegan", "Gluten-Free", "No Cook", "Snack"],
    allergens: ["Tree Nuts"],
    ingredients: [
      "Activated almonds",
      "Cashews",
      "Walnuts",
      "Coconut flakes",
      "Dried cranberries",
      "Golden raisins",
      "72% dark chocolate",
      "Seasonal fresh fruit",
      "Sea salt",
    ],
  },
  {
    id: "quinoa-power-bowl",
    name: "Roasted Veggie Quinoa Bowl",
    description:
      "Tri-color quinoa with roasted sweet potato, crispy chickpeas, kale, and tahini-lemon dressing.",
    longDescription:
      "A vibrant, plant-powered bowl built on a base of tri-color quinoa and massaged lacinato kale. Topped with cumin-spiced roasted sweet potato, crispy oven-roasted chickpeas, sliced avocado, pickled red onion, and pumpkin seeds. Drizzled with our bright tahini-lemon dressing. All components are pre-cooked; just reheat and assemble.",
    category: "lunch-snack",
    images: [
      "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540914124281-342587941389?w=900&auto=format&fit=crop",
    ],
    nutrition: {
      calories: 460,
      protein: 24,
      carbs: 58,
      fat: 16,
      fiber: 8,
      sodium: 540,
    },
    pricing: { serves1: 11.99, serves2: 20.99, family: 37.99 },
    prepTime: "10 min",
    cookTime: "5 min (reheat)",
    tags: ["Vegan", "Gluten-Free", "High Fiber"],
    allergens: ["Sesame"],
    ingredients: [
      "Tri-color quinoa",
      "Lacinato kale",
      "Sweet potato",
      "Chickpeas",
      "Avocado",
      "Red onion",
      "Pumpkin seeds",
      "Tahini",
      "Lemon",
      "Ground cumin",
    ],
    isNew: true,
  },
];

export function getMealById(id: string): Meal | undefined {
  return meals.find((m) => m.id === id);
}

export function getDinners(): Meal[] {
  return meals.filter((m) => m.category === "dinner");
}

export function getBreakfasts(): Meal[] {
  return meals.filter((m) => m.category === "breakfast");
}

export function getLunchSnacks(): Meal[] {
  return meals.filter((m) => m.category === "lunch-snack");
}
